### PR TITLE
Test 4001: check that TEE_DigestDoFinal() resets the state

### PR DESCRIPTION
**Pull request by jforissier**
This is to validate https://github.com/OP-TEE/optee_os/pull/420.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
Test 4002 updated, too, to check `TEE_MACComputeFinal()`.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
Actually I think we should ignore the second patch (test 4002), see https://github.com/OP-TEE/optee_os/pull/420#issuecomment-126252190.

**Comment by pascal-brand-st-dev** [comment]
We could check MacFinal panics the second time. But I'm also OK to remove the MacFinal test.

**Comment by jforissier** [comment]
OK let's address `TEE_DigestDoFinal()` only here. I have reverted the bad commit.

**Comment by jforissier** [comment]
Squashed with review tag added.

**Pull request merged**
