### PR TITLE
GP11 : TEE_GetOperationInfoMultiple

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by cedric-chaumont-st-dev** [comment]
Update.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by cedric-chaumont-st-dev** [comment]
Rebased. Squashed. Tested (STM, ARM Juno).
29320 subtests of which 0 failed
687 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Comment by cedric-chaumont-st-dev** [comment]
Tested (STM, ARM Juno).
29320 subtests of which 0 failed
687 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Pull request merged**
