### PR TITLE
Call TEEC_AllocateSharedMemory with TEEC_MEM_* Fixes #90

### LINKED ISSUE #90: TEEC_AllocateSharedMemory with TEEC_MEMREF_PARTIAL_OUTPUT/INPUT
Hi,

I've found here (GP tests):
https://github.com/OP-TEE/optee_test/blob/master/host/xtest/xml/include/xml_crypto_api.h#L808

that sometimes you use TEEC_MEMREF_PARTIAL_OUTPUT (INPUT) flag when calling TEEC_AllocateSharedMemory. Shouldn't it be a TEEC_MEM_OUTPUT(INPUT) flag instead?

I think TEEC_MEMREF_PARTIAL shouldn't  be used for TEEC_AllocateShareMemory, isn't? As far as I understand it is useful when constructing param types with TEEC_PARAM_TYPES(). Or am I completely wrong?

### PR DESCRIPTION
**Pull request by flowher**
As per "4.3.6 TEEC_SharedMemory" of TEE_Client_API_Spec-v1.0_c the flags field of TEEC_SharedMemory can contain either TEEC_MEM_INPUT or TEEC_MEM_OUTPUT. All other bits in this field SHOULD be set to zero.

Signed-off-by: Krzysztof Kwiatkowski <kris@amongbytes.com>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
I've reviewed and tested this on latest, all good. Can you please just change the commit message slightly? We're not super strict, but we normally try to follow the [50/72 "rule"](http://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting) if possible. A suggestion for another commit message would be:

```
Change parameters to TEEC_AllocateSharedMemory

As discussed in https://github.com/OP-TEE/optee_test/issues/90 we're
changing from using TEEC_MEMREF_PARTIAL_INPUT to instead use
TEEC_MEM_INPUT (and the same for OUTPUT).

Signed-off-by: Krzysztof Kwiatkowski <kris@amongbytes.com>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU)
```

**Comment by flowher** [comment]
Done, Thanks !

**Comment by jbech-linaro** [comment]
@flowher thanks, to make it a bit easier for us when merging, can I ask you for another favor?
1. Please squash all commits to single commit (something like: `git rebase -i b477cc9fc995ec18708d4d5e0fd4dd7c1a3b06f4^1`)
2. Then force push it to your own development branch (something like: `git push -f <remote> issue_90`)

Doing so makes life easier for the OP-TEE admin pushing it to the master branch.

**Comment by flowher** [comment]
Ok, done.
Thanks for instructions

**Comment by jbech-linaro** [comment]
The patch has been merged, thanks a lot @flowher for the contribution (and doing the rebase etc).

**Pull request merged**
