### PR TITLE
GP11 : TEE Arithmetical API fix/panic reason

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

To be merged at the same time as https://github.com/OP-TEE/optee_os/pull/383

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by cedric-chaumont-st-dev** [comment]
Rebased. Tested (STM, ARM Juno)
28716 subtests of which 0 failed
687 test cases of which 0 failed
0 test case was skipped
TEE test application done!
Note: Use

**Comment by pascal-brand-st-dev** [comment]
@cedric-chaumont-st-dev Can you update the tags so that I can push? Thanks.

**Comment by cedric-chaumont-st-dev** [comment]
Updated.

**Pull request merged**
