### PR TITLE
Sync with secure storage updates

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Needs https://github.com/OP-TEE/optee_os/pull/1481 for tests to pass

### CODE REVIEW

**Comment by jforissier** [comment]
In commit "core: FS: key manager takes supplied UUID", I think you should say in the commit description that the removed test is not applicable since there is no per-TA directory anymore. In any case:

`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
@jforissier, you mean commit "regression: 6015: remove special case for REE FS"?

**Comment by jforissier** [comment]
Yes, indeed (wrong copy/paste!)

**Comment by jenswi-linaro** [comment]
Commit message updated, tags applied and rebased.

**Pull request merged**
