### PR TITLE
regression 4006: add test cases for SM2 PKE

### PR DESCRIPTION
**Pull request by jforissier**
Test cases for ~~https://github.com/OP-TEE/optee_os/pull/3500~~ Edit: https://github.com/OP-TEE/optee_os/pull/3504.

### CODE REVIEW

**Comment by jforissier** [comment]
Forced pushed to trigger IBART after SM2 PKE was merged in optee_os master.

**Comment by jforissier** [comment]
The IBART SM2 test case passed, but "regression_6016 Storage concur[r]ency" deadlocked. It is the second time I'm seeing this in a few days. I'm going to restart the IBART run, and we will hopefully find out more during the 3.8.0 release testing...

**Comment by jforissier** [comment]
More about the IBART failure here: https://github.com/OP-TEE/optee_os/issues/3518.

**Comment by jforissier** [comment]
Ping!

IBART failure was fixed in https://github.com/OP-TEE/optee_os/pull/3524.

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
