### PR TITLE
xtest: regression_6000.c: decrease NUM_THREADS to 3

### PR DESCRIPTION
**Pull request by maroueneboubakri**
As per the other regression tests implying concurrency, decrease the number of threads to 3 to satisfy other platforms limitation.
Discussion https://github.com/OP-TEE/optee_test/pull/47

Signed-off-by: Marouene Boubakri <marouene.boubakri@nxp.com>

### CODE REVIEW

**Review by jforissier — COMMENTED** [review]
Perhaps it would be good to mention the platform that needs this to pass the test at the moment (riscv plat-virt?). Otherwise LGTM.

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by maroueneboubakri** [comment]
> 

Yes, RISC-V vrit has up to to 8 cores, that's not a real issue, other RISC-V platforms emulated on QEMU have 4 cores. That's to have common testing basis.

**Comment by etienne-lms** [comment]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by maroueneboubakri** [comment]
Tags applied.

**Comment by jenswi-linaro** [comment]
What problem are we fixing here?

**Comment by maroueneboubakri** [comment]
> What problem are we fixing here?

Out of memory on QEMU RISC-V Vrit.

**Comment by jenswi-linaro** [comment]
What kind of memory? Can't load four storage TAs, out of heap, out of shared memory?

**Pull request closed without merging**
