### PR TITLE
xtest_1000: define a different TA_DIR for __ANDROID__

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by vchong** [comment]
Tag added. Ok to merge? Thanks!

**Comment by jforissier** [comment]
@vchong if I'm not mistaken the commit subject is wrong. You make your commit sound like you're changing the TA_DIR path for Android, which is not the case. You're just changing the place where it is defined.

**Comment by jforissier** [comment]
Commit message reworded and patch merged.

**Comment by vchong** [comment]
Thanks!

**Pull request closed without merging**
