### PR TITLE
xtest 6012: Persistent File Creation

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
Test with specific persistent file creation:
optional object, and creation overwrite.

This reproduces https://github.com/OP-TEE/optee_os/issues/745

Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Thanks for adding this test, now we just need to fix the problem too. :-)

Please add a brief description of the problem in the commit message.

With or without my comment addressed:
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
:smile:  I am working on it.

**Comment by pascal-brand-st-dev** [comment]
updated

**Comment by pascal-brand-st-dev** [comment]
It has been manually merged too

**Pull request closed without merging**
