### PR TITLE
Update host/openssl/lib/arm/libcrypto.a with -fPIC

### PR DESCRIPTION
**Pull request by jforissier**
Replace the pre-built Arm 32-bit OpenSSL crypto library with the same,
built with -fPIC for position-independent code. Some "hardened"
environments require PIC, and therefore this new version should provide
wider compatibility.

Note that it is always possible to specify a custom OpenSSL library at
build time via OPTEE_OPENSSL_EXPORT, but having something more likely to
work out of the box is nice.

The build steps for the new libcrypto.a are:

```
 git clone https://github.com/openssl/openssl.git
 cd openssl
 git checkout OpenSSL_1_0_2o
 ./Configure linux-generic32 -mcpu=cortex-a9 no-shared \
             --cross-compile-prefix=arm-linux-gnueabihf- \
            -fPIC
 make build_libcrypto
```
Suggested-by: Markus S. Wamser <github-dev@mail2013.wamser.eu>
Link: https://github.com/OP-TEE/optee_test/issues/507
Signed-off-by: Jerome Forissier <jerome@forissier.org>

### CODE REVIEW

**Comment by jforissier** [comment]
@wamserma let me know if you are OK with the `Suggested-by:`, thanks.

**Comment by wamserma** [comment]
@jforissier Please use
Suggested-by: Markus S. Wamser markus.wamser@mixed-mode.de
for this one.

**Comment by jforissier** [comment]
@wamserma sure, patch updated.

**Comment by wamserma** [comment]
@jforissier You can also add: 
Tested-by: aleksandar.nikolic@mixed-mode.de

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by wamserma** [comment]
Closes https://github.com/OP-TEE/optee_test/issues/507

**Pull request merged**
