### PR TITLE
Android.mk : Fix compilation for build outside of source

### PR DESCRIPTION
**Pull request by FunduBits**
Trying to specify Android build location outside of souce directory's default 'out'
using OUT_DIR_COMMON_BASE env variable, results in the following error
"....
build/core/binary.mk:1480: error: external/optee_test/Android.mk:
xtest: C_INCLUDES must be under the source or output directories:
"
Fix the error by moving host_include/ from LOCAL_C_INCLUDES to LOCAL_CFLAGS

Signed-off-by: Jassi Brar <jaswinder.singh@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
@liuyq fyi

Need some time to test this first to make sure it doesn't break current builds. Please hold for updates. Thanks!

@glneo Can you maybe suggest an alternative patch/PR?

**Comment by FunduBits** [comment]
Yes, please this or any other way you deem appropriate.
Android builds just fine with and without OUT_DIR_COMMON_BASE pointing to some external location.
It is the OPTEE packages, that break the build for OUT_DIR_COMMON_BASE.

**Comment by vchong** [comment]
```
Tested-by: Victor Chong <victor.chong@linaro.org> (hikey620)
Acked-by: Victor Chong <victor.chong@linaro.org>
```

@liuyq are you ok with this?

**Comment by vchong** [comment]
Related to https://github.com/OP-TEE/optee_os/pull/2470

**Comment by liuyq** [comment]
looks OK to me.

**Comment by vchong** [comment]
@jforissier ok to merge without manual rebase? Thanks!

**Comment by jforissier** [comment]
@vchong: I feel @glneo's suggestion has not been properly investigated, but I'm OK to pick this (and the optee_os patch) as a quick fix at least.
I will apply the tags and merge manually.

**Comment by jforissier** [comment]
Merged manually.

**Pull request closed without merging**
