### PR TITLE
Android.mk fixes

### PR DESCRIPTION
**Pull request by kuscsik**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by kuscsik** [comment]
Added "Reviewed-by" for reviewers.

**Pull request merged**
