### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jforissier** [comment]
About the first patch: I suppose optee_os has to be built with `CFG_TEE_CORE_EMBED_INTERNAL_TESTS=y`, which is not the default for all platforms currently. So, either optee_os should be updated or test 1001 should not fail when the static TA is not available.

**Comment by jenswi-linaro** [comment]
Update

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied

**Comment by pascal-brand-st-dev** [comment]
@jenswi-linaro Could rebase on master? Thanks.

**Comment by jenswi-linaro** [comment]
Rebased

**Pull request merged**
