### PR TITLE
regression 4002: add CMAC test case with a 16 bytes increment

### PR DESCRIPTION
**Pull request by clementfaure**
Hello,

@jforissier
The test to add is in the end very simple ... just one `XTEST_MAC_CMAC_CASE` :)
Should I specify in the commit message, that it's related to the CAAM? I don't know if I should since this test is generic and the CAAM platform specific ..

Please refer to https://github.com/OP-TEE/optee_os/pull/4583

Thanks

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
If you're targeting a bug that is supposed to be fixed please mention that in the commit message. A link to https://github.com/OP-TEE/optee_os/pull/4583 in the commit message should be useful.

**Review by jforissier — APPROVED** [review]
Please add:
```
Link: https://github.com/OP-TEE/optee_os/pull/4583
Signed-off-by: ...
```
...to the commit description as suggested by Jens. With that:

`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

Thanks!

**Comment by clementfaure** [comment]
@jenswi-linaro @jforissier Commit reworded!

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
"does not properly handle"? That was the problem that was fixed, right? So you can't say that. Instead "This is a test case for a bug in the CAAM driver which would not handle... [1]" and `Link: [1] https://...`.

**Comment by clementfaure** [comment]
Indeed, that's not well written 🤦 .
Let me fix that

**Pull request merged**
