### PR TITLE
Add xtest filtering level (xtest lite)

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
RSA/DSA/ECDSA/ECDH
default: sanity test suite (level=0)
usage: xtest -h

Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by cedric-chaumont-st-dev** [comment]
@pascal-brand-st-dev : sanity/full should be taken into account because of 'goto run;'

**Comment by pascal-brand-st-dev** [comment]
@cedric-chaumont-st-dev You're right, I missed it. However, I do not find it clean in the way "if -t option is there, then -l option is forgiven". I would drop sanity/full, and only keep -l option. @jforissier what do you think?

**Comment by jforissier** [comment]
@pascal-brand-st-dev I agree. We should add `-t` later if/when we integrate benchmark (performance) tests, in which case `-t` could combine nicely with `-l`. But I don't think it is a good idea to use `-t something` as a synonym for `-l x`.

**Comment by cedric-chaumont-st-dev** [comment]
okidoki.

**Comment by cedric-chaumont-st-dev** [comment]
Update.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by cedric-chaumont-st-dev** [comment]
Rebase. Squash. Verify (STM, AR Juno)
44893 subtests of which 0 failed
688 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Pull request merged**
