### PR TITLE
Update GP suite

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Needs to be tested and merged together with https://github.com/OP-TEE/build/pull/440

**Comment by jforissier** [comment]
It's a good thing to be able to run the latest GP compliance suite with OP-TEE! :+1: 

- For commit "regression: remove 7000 series", "regression: remove GP test code from 6000 series", "
xtest: remove GP test TA UUID":
`Reviewed-by: Jerome Forissier <jerome@forissier.org>`
- For commit "gp: update compliance suite to version 2.0.0.2":
`Acked-by: Jerome Forissier <jerome@forissier.org>`

@jbech-linaro 
Since this PR removes some code which was testing the same things as some GP tests, there will be a smaller test coverage for people who don't have access to the GP test suite. Can we expect IBART to run with GP tests enabled to mitigate this perhaps?

**Comment by jbech-linaro** [comment]
> Can we expect IBART to run with GP tests enabled to mitigate this perhaps?

That's the idea and after having a chat with Jens it seems like run-time etc isn't too bad. Maybe I'll limit to run it on either HiKey or QEMU to start with. The IBART "server" is an old laptop from 2013, so there isn't too much "umph" on it :)
FYI --> [LOC-343](https://projects.linaro.org/browse/LOC-343).

**Comment by jenswi-linaro** [comment]
Tags applied. Note that "Remove unused ta/include/GP_defs.h" still lacks a tag.

**Comment by jforissier** [comment]
> Note that "Remove unused ta/include/GP_defs.h" still lacks a tag.

I missed it ;-)
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Pull request merged**
