### PR TITLE
xtest: sort cases to use a well defined order

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Prior to this patch was the order of the cases depending on link order
and in which order constructors are called inside an object file. To use
a well defined order, sort the cases while registering them.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
I'm not sure what happened in `regression_6018.3`.

**Comment by etienne-lms** [comment]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
