### PR TITLE
Pgt alloc test

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Depends on https://github.com/OP-TEE/optee_os/pull/729

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
Require an update of Android.mk, and a new Android.mk in the TA repository.

**Comment by jenswi-linaro** [comment]
Added `Android.mk`, applied R-B tag.

**Comment by pascal-brand-st-dev** [comment]
`optee_test/Android.mk` must contain
`LOCAL_C_INCLUDES += $(LOCAL_PATH)/ta/concurrent_large/include`

**Comment by jenswi-linaro** [comment]
Sorry, missed that, updated now.

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied.

**Pull request merged**
