### PR TITLE
Fix compilation issue when TRACE_LEVEL > TRACE_DEBUG

### PR DESCRIPTION
**Pull request by sakjain92**
Signed-off-by: Saksham Jain <saksham.jain@nxp.com>

### CODE REVIEW

**Comment by jforissier** [comment]
This is when `TRACE_LEVEL >= TRACE_DEBUG`, right?
With the commit comment fixed:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
Can you finalize your contribution as described in https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md#finalizing-the-contribution?
Let me know if you need help on this.

**Comment by jbech-optee-adm** [comment]
Closing the PR since it has been merged manually.

**Pull request closed without merging**
