### PR TITLE
os_test: add basic tests for floating point

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Adds basic test for floating point.
Depends on https://github.com/OP-TEE/optee_os/pull/584

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Seems good to me, may I just ask what the `_subj` stands for in some file names?
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
subj as in test subject :-)

**Comment by jbech-linaro** [comment]
That was what I suspected, but I wasn't sure =)

**Comment by jenswi-linaro** [comment]
Use `CFG_TA_FLOAT_SUPPORT` to tell if floating point should be tested.

**Comment by jenswi-linaro** [comment]
Sorry about the mess, propagating CFG_TA_FLOAT_SUPPORT to TA dev kit has to wait until I've fixed hard-float.

**Comment by jenswi-linaro** [comment]
Rebased
Propagating CFG_TA_FLOAT_SUPPORT to TA dev kit now works properly which means that floating point tests only are enabled when CFG_TA_FLOAT_SUPPORT is y.

**Comment by jenswi-linaro** [comment]
@jbech-linaro still OK with the PR?

**Comment by jbech-linaro** [comment]
Yes, looks good to me.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jenswi-linaro** [comment]
Added tags

**Pull request merged**
