### PR TITLE
Multiple persistent object manipulation

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
xtest 6014 is introduced. It highlights an issue when persistent
objects are manipulated in a loop.
cf. https://github.com/OP-TEE/optee_os/issues/798

Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
It should not be merged while a fix is not available.

**Comment by jenswi-linaro** [comment]
Fix in https://github.com/linaro-swg/linux/pull/10

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
Huh, GitHub magic, when I merged https://github.com/linaro-swg/linux/pull/10 I automatically closed this PR also. I can fix it, but I was a bit surprised that it did this automatically since I've never seen that happening before.

**Comment by jbech-optee-adm** [comment]
Closing the PR since it has been merged manually.

**Pull request closed without merging**
