### PR TITLE
Android.mk: Rename C source files to its test suite

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
@liuyq @vishalbhoj fyi this depends on https://github.com/OP-TEE/optee_test/commit/cd0186b3bf0698affa09245f855dce3254858322 to apply cleanly on 2.4.0. Or we just don't rename 10000 -> 8000 and 20000 -> 9000 in this patch.

There's another issue though: https://github.com/OP-TEE/optee_test/issues/201.

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by vchong** [comment]
Tag added. Depends on #203.

**Comment by jforissier** [comment]
Rebased on top of master and merged. Thanks! (and apologies for overlooking this)

**Pull request closed without merging**
