### PR TITLE
Avoid writing to the TA directory

### PR DESCRIPTION
**Pull request by d3zd3z**
Presuming that the tee-supplicant is configured to support loading TAs
from an alternate path, use this alternate path to write test TAs,
instead of trying to rename and overwrite the existing TA images.
This gives several benefits:

- The tests no longer assume that the TA directory is writable.  This
  allows this test to pass on platforms where it is not.

- There is no longer a race with pressing Ctrl-C at an inopportune
  time will leave a corrupted TA file in place instead of the correct
  one.

This change affects test 1008.4 and 1008.5, "Load fake uuid TA", and
"Load corrupt TA".

Signed-off-by: David Brown <david.brown@linaro.org>

### CODE REVIEW

**Comment by d3zd3z** [comment]
This depends on [optee_client#54|https://github.com/OP-TEE/optee_client/pull/54] in order to load the TAs. Without it, the tests will fail because the supplicant will continue loading the non-corrupt TA.

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)`

**Comment by d3zd3z** [comment]
Squashed, and applied review tags.

**Comment by jforissier** [comment]
I was faster than you ;) could you please rebase and re-push?

**Comment by d3zd3z** [comment]
We prefer rebasing to merges?

**Comment by jforissier** [comment]
Yes, to keep the commit history as clean and linear as possible.

**Pull request merged**
