### PR TITLE
Panic instance

### PR DESCRIPTION
**Pull request by omihalac**
This could be consider a rework of [PR#347](https://github.com/OP-TEE/optee_test/pull/347) that brings on top of the main implementation some code changes for stability.

However, the issue raised in OP-TEE/optee_os#3067 cannot be reproduce by these tests whatsoever.

### CODE REVIEW

**Comment by jforissier** [comment]
Hi @omihalac,

Thanks for the patches. Without looking further into the actual changes, I have two comments:
1. If the patches come from another PR and have been non-trivially modified, they should not bear any `Acked-by:` or `Reviewed-by:` tag.
2. Similarly, since @etienne-lms is the original author (as properly indicated by the Author field in the commit, which is fine), I think we could use the `Co-Developped-by:` tag documented for the Linux kernel [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/5.Posting.rst?h=v5.3#n211). Like so:

```
Commit subject goes here

Blah blah commit description

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Co-Developped-by: Ovidiu Mihalachi <ovidiu_mihalachi@mentor.com>
Signed-off-by: Ovidiu Mihalachi <ovidiu_mihalachi@mentor.com>
[Review/Ack tags when available]
```

**Comment by jforissier** [comment]
Well since the differences between #347 and this is minimal (below, after rebasing both branches onto master), I suggest they should be taken in the original PR.

```diff
diff --git a/host/xtest/regression_1000.c b/host/xtest/regression_1000.c
index 4bbba85..f547454 100644
--- a/host/xtest/regression_1000.c
+++ b/host/xtest/regression_1000.c
@@ -1639,9 +1639,8 @@ static void test_panic_ca_to_ta(ADBG_Case_t *c, const TEEC_UUID *uuid,
                goto bail0;
 
        exp_res = multi_instance ? TEEC_SUCCESS : TEEC_ERROR_TARGET_DEAD;
-       if (!ADBG_EXPECT_TEEC_RESULT(c, exp_res,
-                                    sims_get_counter(&cs[0], &counter)))
-               goto bail1;
+       ADBG_EXPECT_TEEC_RESULT(c, exp_res, sims_get_counter(&cs[0], &counter));
+       goto bail0;
 
 bail2:
        TEEC_CloseSession(&cs[2]);
diff --git a/ta/sims/include/ta_sims_test.h b/ta/sims/include/ta_sims_test.h
index e7f4f92..e91aadc 100644
--- a/ta/sims/include/ta_sims_test.h
+++ b/ta/sims/include/ta_sims_test.h
@@ -80,7 +80,7 @@
 #define TA_SIMS_CMD_PANIC              4
 
 /*
- * TA_SIMS_OPEN_TA_SESSION     Open a session towards a TA
+ * TA_SIMS_CMD_OPEN_TA_SESSION Open a session towards a TA
  *
  * param#0: [in]       memref = target TA UUID
  */
```

**Comment by omihalac** [comment]
> Well since the differences between #347 and this is minimal (below, after rebasing both branches onto master), I suggest they should be taken in the original PR.

This was my first intention, but keeping in mind you indicate in a similar case that I should open a new PR with my patch (see [comment](https://github.com/OP-TEE/optee_test/pull/347#issuecomment-529912816)), I thought it would speed up a bit the update process.

In this case whether @etienne-lms should adopt and rebase the updates from this PR or I could send in [PR#347](https://github.com/OP-TEE/optee_test/pull/347) a patch.

**Comment by jforissier** [comment]
> or I could send in PR#347 a patch.

Just add a couple comments in the PR like we do for all reviews...

**Pull request closed without merging**
