### PR TITLE
Android.mk: Add missing include dirs

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
#358 should be merged first.

**Comment by jforissier** [comment]
Does this fix a build on AOSP? If so, how come we meet the issue only now? (some paths have been existing for quite some time).

**Comment by vchong** [comment]
I've the same question myself. Testing right now.

**Comment by vchong** [comment]
Ok, the TA include dirs are only needed if one of the header files is used by `host/xtest/*`, so I'll close this. Sorry for the noise.

**Comment by jforissier** [comment]
Ok, so now I'm wondering, perhaps some of those paths are not needed and could be removed?

**Comment by vchong** [comment]
> Ok, so now I'm wondering, perhaps some of those paths are not needed and could be removed?

Nope. Already checked. All existing ones are used. ; )

**Comment by jforissier** [comment]
Excellent :)  Thanks!

**Pull request closed without merging**
