### PR TITLE
TA rpc_test: change to multi-instance

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Change the rpc_test TA from single-instance to multi-instance to let
the test case work even when deadlock avoidance is enabled in TEE Core.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU)

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jenswi-linaro** [comment]
Tags applied.

**Comment by pascal-brand-st** [comment]
Manually merged

**Pull request closed without merging**
