### PR TITLE
xtest_20000.c: Fix fopen() mode string

### PR DESCRIPTION
**Pull request by jforissier**
The correct fopen() mode string to open an existing file in read/write
mode and set the stream pointer at the beginning is 'r+'.
'rw+' is invalid and causes the file to be open read-only on Android.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
Tags applied.

**Comment by jforissier** [comment]
Oops! Commit e6ef561 contains a file that should not be there (Android.mk) -- mistakenly added when I added the Reviewed-by: tags. This has been fixed manually (commit 679ee82 force-pushed to master).

**Pull request merged**
