### PR TITLE
xtest_20000: Fix uninitialized variable warning

### PR DESCRIPTION
**Pull request by glneo**
When compiled with -Wuninitialized, GCC identifies a false positive
uninitialized variable 'real_offset'. Although we know the default
path will not be taken, GCC does not, for good measure lets just pass
back an error to fix the warning.

Signed-off-by: Andrew F. Davis <afd@ti.com>

### CODE REVIEW

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

@jforissier, you can choose between 2 variants of the fix (https://github.com/OP-TEE/optee_test/pull/176 or https://github.com/OP-TEE/optee_test/pull/179). You are lucky today!

**Comment by jforissier** [comment]
@etienne-lms let's proceed with this one since it addresses your comment. @jenswi-linaro you have given your R-b for the other version, are you OK with this one?

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by glneo** [comment]
Updated with Reviewed-by

**Comment by jforissier** [comment]
Rebased on top of master and merged. Thanks!

**Pull request closed without merging**
