### PR TITLE
Fix xtest with GP testsuite

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>
    Tested-by: Pascal Brand <pascal.brand@linaro.org> (QEMU)

**Comment by cedric-chaumont-st-dev** [comment]
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (STM boards)
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (ARM Juno board)

**Comment by cedric-chaumont-st-dev** [comment]
Updated.

**Comment by cedric-chaumont-st-dev** [comment]
Rebased

**Pull request merged**
