### PR TITLE
GP11 : ECDH NIST test vectors

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

Would now require a runtime option to have "light" xtests

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)`

**Comment by pascal-brand-st-dev** [comment]
Please add the tags

**Comment by cedric-chaumont-st-dev** [comment]
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (STM boards)
Update git commit message.

**Comment by pascal-brand-st** [comment]
Manually merged

**Pull request closed without merging**
