### PR TITLE
xtest: pkcs11_1000.c: Test support of object checksum value computation

### PR DESCRIPTION
**Pull request by maroueneboubakri**
This test involves `PKCS11_CKA_CHECK_VALUE ` when enabled, as per the spec, the attribute can be either the legitimate value recomputed by the PKCS#11 token or a zero-sized value called a no-value for when client does not want the attribute to set in an object. This test invokes Cryptoki API functions `C_GenerateKey()`, `C_CreateObject()`, `C_CopyObject()`, `C_SetAttributeValue()`, `C_UnwrapKey()` and `C_DeriveKey()` to perform check value computation and this test query the value using `C_GetAttributeValue()`.

### CODE REVIEW

**Comment by maroueneboubakri** [comment]
Updated the test with the following: 
- Set the expected KCV for `C_UnwrapKey()` instead of preventing it from generation (already tested)
- Destory the attribute using `C_SetAttributeValue()`

**Comment by etienne-lms** [comment]
@maroueneboubakri, could you pick the [review] patches i've added in https://github.com/etienne-lms/optee_test/commits/dev-pkcs11/ and apply the content you're happy with  to this P-R. That would add few more test cases.

**Comment by maroueneboubakri** [comment]
> @maroueneboubakri, could you pick the [review] patches i've added in https://github.com/etienne-lms/optee_test/commits/dev-pkcs11/ and apply the content you're happy with to this P-R. That would add few more test cases.

Done !

```
# xtest -t pkcs11 1029
Test ID: 1029
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# pkcs11
#
######################################################
 
* pkcs11_1029 PKCS11: Test support for object checksum value computation
o pkcs11_1029.1 Compute KCV on C_GenerateKey()
  pkcs11_1029.1 OK
o pkcs11_1029.2 Set no-value KCV on C_CreateObject()
  pkcs11_1029.2 OK
o pkcs11_1029.3 Set invalid KCV on C_CreateObject()
  pkcs11_1029.3 OK
o pkcs11_1029.4 Set KCV on C_CreateObject()
  pkcs11_1029.4 OK
o pkcs11_1029.5 Copy and recompute KCV on C_CopyObject()
  pkcs11_1029.5 OK
o pkcs11_1029.6 Set no-value KCV on C_CopyObject()
  pkcs11_1029.6 OK
o pkcs11_1029.7 Set invalid KCV on C_CopyObject()
  pkcs11_1029.7 OK
o pkcs11_1029.8 Compute KCV on C_DeriveKey()
  pkcs11_1029.8 OK
o pkcs11_1029.9 Compute KCV on C_UnwrapKey()
  pkcs11_1029.9 OK
o pkcs11_1029.10 Destroy KCV using C_SetAttributeValue()
  pkcs11_1029.10 OK
o pkcs11_1029.11 Create an invalid KCV using C_SetAttributeValue()
  pkcs11_1029.11 OK
o pkcs11_1029.12 Set KCV of invalid size using C_SetAttributeValue()
  pkcs11_1029.12 OK
o pkcs11_1029.13 Set valid KCV using C_SetAttributeValue()
  pkcs11_1029.13 OK
  pkcs11_1029 OK
+-----------------------------------------------------
Result of testsuite pkcs11 filtered by "1029":
pkcs11_1029 OK
+-----------------------------------------------------
54 subtests of which 0 failed
1 test case of which 0 failed
29 test cases were skipped
TEE test application done!

```

**Comment by etienne-lms** [comment]
Thanks. You can remove my `Co-developed-by` tag and replace it with
`Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>`. This is your work i've just extended.

**Comment by jforissier** [comment]
If I'm not mistaken, the feature tested here is not enabled by default and not tested by CI. Could we have it enabled by default on QEMUv8 or else add `CFG_PKCS11_TA_CHECK_VALUE_ATTRIBUTE=y` in the QEMUv8 CI job please?

**Comment by etienne-lms** [comment]
Yes, indeed, we should set `CFG_PKCS11_TA_CHECK_VALUE_ATTRIBUTE=y` for Qemu CI tests. I'll append that change to P-R https://github.com/OP-TEE/optee_os/pull/6550.

**Comment by maroueneboubakri** [comment]
Tag applied.

**Comment by maroueneboubakri** [comment]
@jforissier could you also merge this PR ?

**Comment by jforissier** [comment]
@maroueneboubakri yes but I'd rather do it after the optee_os PR is merged so I can make sure CI is happy with the feature enabled.

**Comment by etienne-lms** [comment]
Successfully tested on qemu_virt with https://github.com/OP-TEE/optee_os/pull/6579 applied.

**Comment by jforissier** [comment]
CI jobs restarted in order to check if all is good with https://github.com/OP-TEE/optee_os/pull/6579 which was merged minutes ago.

**Comment by etienne-lms** [comment]
I missed that I had patches from P-R #6550 in my test setup.
Pkcs11 TA key check value need the fix from commit "ta: pkcs11: preserve object when set attribute fails".
The other fix (commit "ta: pkcs11: treat bad KCV size as a bad value case") is welcome but not covered by current test.
I'll update P-R #6550 to rebase these 2 commits. They have no review tag up to now.

**Comment by etienne-lms** [comment]
CI tests are fine.

**Comment by etienne-lms** [comment]
Thanks

**Pull request merged**
