### PR TITLE
distributed registration of test cases

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`
need to be rebased.

**Comment by etienne-lms** [comment]
@jenswi-linaro. my r-b is a bit anticipated. Missing updates regarding GP TestSuite in commit "xtest: distributed registration of cases". Can you have a look at https://github.com/etienne-lms/optee_test/commit/24dd8233193dcdb756bc59ac6c7bf5c16cfedcdb, and squash into your last commit if feel it's ok. Note: i have rebased your patch to produce this proposal (tested on qemu).

**Comment by jenswi-linaro** [comment]
Squashed, rebased and tag applied. @etienne-lms, I took the liberty to add a few other tags from you in the last commit.

@jforissier, I leave it to you to decide if you want this in the release or not.

**Comment by etienne-lms** [comment]
i'm fine with the content, my r-b still applies (eventually you can remove my s-o-b from last commit and keep only the r-b and tested-by, to prevent my s-o-b + r-b in same commit).

**Comment by jenswi-linaro** [comment]
@etienne-lms, you've contributed code so I think your s-o-b is important. I don't a problem with both a s-o-b and r-b tag, but if you'd like to have something changed I'll do that.

**Comment by etienne-lms** [comment]
ok. current state is fine to me.

**Comment by jenswi-linaro** [comment]
Rebased

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
