### PR TITLE
xtest: add --stats applet

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Adds the --stats applet to interact with the pseudo TA "stats".

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Very good idea! I was about to do the same a few days ago, based on my [tee-stats](https://github.com/jforissier/tee-stats) project, but then I realized my code was quite outdated and I postponed... :-/

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Comment by jenswi-linaro** [comment]
Hopefully fixing the printf() problem.

**Comment by jforissier** [comment]
All good, thanks.

**Pull request merged**
