### PR TITLE
Add 128 bit key test to 3DES CMAC

### PR DESCRIPTION
**Pull request by uglym8**
To test whether 128 bit keys are handled correctly by 3DES CMAC implementation.
See https://github.com/OP-TEE/optee_os/pull/4466 for more details.

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
Thanks for the patch. I suggest adding prefix "regression 4002:" to the commit subject. Anyways:
`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@uglym8 can you please add your Signed-off-by: and the review/ack tags? Thanks.

**Comment by uglym8** [comment]
Sorry for keeping you waiting guys.
I'll get back to this in a very short time.

**Pull request closed without merging**
