### PR TITLE
Tests for TEE_MACCompareFinal()

### PR DESCRIPTION
**Pull request by jforissier**
Depends on https://github.com/OP-TEE/optee_os/pull/4735.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jforissier** [comment]
Following https://github.com/OP-TEE/optee_os/pull/4735#issuecomment-876298090 I am closing this, and will create a new PR with the first commit only.

**Comment by jforissier** [comment]
> `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

Oops! Sorry Etienne I forgot to add your tag in the new PR :-/

**Pull request closed without merging**
