### PR TITLE
Changing from old STM CLA to the new DCO

### PR DESCRIPTION
**Pull request by jbech-linaro**
`Signed-off-by: Joakim Bech <joakim.bech@linaro.org>`

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jbech-linaro** [comment]
@jenswi-linaro had a comment in optee_client that also applies to this, so I did that update, and also chmod the Notice.md to 644 instead of 744.

Rebased and tags has been applied, ready to be merged.

**Comment by jenswi-linaro** [comment]
With Pascals comment addressed:
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by jbech-linaro** [comment]
Pending fix applied, rebased and tags applied.

**Pull request merged**
