### PR TITLE
sdp: add secure data path tests to Android.mk

### PR DESCRIPTION
**Pull request by kuscsik**

### CODE REVIEW

**Comment by jforissier** [comment]
Where are `sdp_perf.c` and `sdp_basic.c`?

**Comment by kuscsik** [comment]
Hi @jforissier,

I just noticed that pull/148 is still open. It is part of pull/148. I will add a review comment on the patch

Z

**Comment by jforissier** [comment]
Thanks @kuscsik, I was too lazy to check by myself ;)

**Comment by etienne-lms** [comment]
@kuscsik, are you ok if i merge your changes inside #148 so that they get merged (some day) together ?

**Comment by kuscsik** [comment]
Hi @etienne-lms,

if you can just make the change on #148 that is fine by me.

Thanks,

Z

**Comment by jbech-linaro** [comment]
@kuscsik @etienne-lms are we in sync regarding this pr and #148? I.e., can we close this PR?

**Comment by etienne-lms** [comment]
yes, we can close. Fix related to this PR will be merged through #148.

**Comment by jbech-optee-adm** [comment]
As agreed, closing this PR.

**Pull request closed without merging**
