### PR TITLE
ta: os_test: fix print_properties() indentation

### PR DESCRIPTION
**Pull request by quduoduo1**
ta: os_test: fix print_properties() indentation

Fixes print_properties() indentation as per OP-TEE coding style.

Signed-off-by: Chang YuQing<08182924@cumt.edu.cn>
Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>

### CODE REVIEW

**Review by etienne-lms — CHANGES_REQUESTED** [review]
Please fix commit message by add your full name in your Signed-off-by tag ([see developer-certificate-of-origin](https://optee.readthedocs.io/en/latest/general/contribute.html#developer-certificate-of-origin)) and add my review tag:
```
ta: os_test: fix print_properties() indentation

Fixes print_properties() indentation as per OP-TEE coding style.

Signed-off-by: FULL-REAL-NAME <e-mail-address>
Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>
```
Note you don't need to create a new P-R for these changes. Just fix the comit message and force push to your branch [quduoduo1:1](https://github.com/quduoduo1/optee_test/tree/1).

**Review by etienne-lms — COMMENTED** [review]
Thanks @quduoduo1 for the updates.
The commit message format has issues to be fixed. The patch author must correspond to a Signed-off-by tag. Please fix also the S-o-b tag format: `REALNAME <email-address>` (with `<>` not `()`).

**Comment by jenswi-linaro** [comment]
Is this good to merge?

**Comment by jforissier** [comment]
> Is this good to merge?

It is. Thanks for re-opening, I didn't notice the review tag.

**Pull request merged**
