### PR TITLE
remove deprecated ta/prebuilt/faked_armv7_uta_signed_header.bin

### PR DESCRIPTION
**Pull request by etienne-lms**
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
i think we can merge this.

**Comment by jforissier** [comment]
@etienne-lms indeed, thanks for the heads up.

**Pull request merged**
