### PR TITLE
asymm & symm perfs: fix build errors & minor coding style issues

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by etienne-lms** [comment]
I've updated the series to fix another issue reported on 64bit platforms.

**Comment by jforissier** [comment]
About the QEMUv8 CI error: https://github.com/OP-TEE/optee_test/pull/729

**Comment by etienne-lms** [comment]
Thanks. I'll rebase once #729 is merged.

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
@yuzexiyzx, @omasse-linaro, @clementfaure, are you ok with these changes in the crypto perf tools merged from https://github.com/OP-TEE/optee_test/pull/714 (and https://github.com/OP-TEE/optee_test/pull/706)?

**Comment by etienne-lms** [comment]
Review tag applied.

**Comment by etienne-lms** [comment]
thanks

**Pull request merged**
