### PR TITLE
xtest: use conf.h from OP-TEE OS

### PR DESCRIPTION
**Pull request by jforissier**
Tested on D02 but not on Android. Although the change to `Android.mk` is identical to the one in `host/xtest/Makefile`, it would be good if someone could confirm it's working on Android too.

### CODE REVIEW

**Comment by jforissier** [comment]
Hmmm, I'll fix the typo in the first commit (mey).

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
PR was compile-tested on Android, too.

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Pull request merged**
