### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by glneo**

### CODE REVIEW

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

Thanks for your contribution. In case you don't know the next steps: please update your commits to add my R-b and force push. Then I will merge to master.

**Comment by d3zd3z** [comment]
```
Reviewed-by: David Brown <david.brown@linaro.org>
```

**Comment by jforissier** [comment]
I suppose this should be removed (not used?):
```
OPTEE_CLIENT_PATH ?= $(LOCAL_PATH)/../optee_client
```
https://github.com/OP-TEE/optee_test/blob/master/Android.mk#L10

**Comment by jforissier** [comment]
@glneo care to update the first commit (remove `OPTEE_CLIENT_PATH` from `Android.mk` since this name is obsolete) and rebase on top of current master? Thanks!

**Pull request merged**
