### PR TITLE
xtest storage: can't use object_id from shared memory

### PR DESCRIPTION
**Pull request by etienne-lms**
According to the GP spec V1.1, the object_id in create/open/rename
functions is not allowed to reside in the shared memory. This change
insures the test TAs use local buffers to store the target file ID.

Suggested-by: Zeng Tao <prime.zeng@hisilicon.com>
Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (Qemu, GP)
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

Note: there is no test checking that using object_id from SHM is forbidden. I will look at that.

### CODE REVIEW

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

Thanks for taking care of this!

**Comment by etienne-lms** [comment]
Added a 2nd commit to have a regression test on this.

**Comment by jforissier** [comment]
No please don't add the second test here because I'd like to merge this first, then check that the optee_os PR is OK (CI will use the new `xtest`), then I can merge the optee_os PR. Only after I will  take the new test.
Thanks.

**Comment by etienne-lms** [comment]
ok.

**Comment by etienne-lms** [comment]
Tag applied.

**Comment by jforissier** [comment]
Thanks!

**Pull request merged**
